name: Deploy Website

on:
  push:
    branches:
      - main  # Bleibt auf "main", weil deine index.html dort liegt

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Deployment auf GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main  # Bleibt "main"
          folder: .  # Falls dein Code in einem Unterordner ist, passe das an
