name: Deploy Website

on:
  push:
    branches:
      - main  # Trigger auf Änderungen im "main"-Branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: GitHub Pages neu deployen
        run: |
          git fetch --unshallow
          git push origin main
